---
title: "Chenopodium Freeze-Survival"
author: "Daniel R Williams"
date: "12/11/2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}

library(knitr)
knitr::opts_chunk$set(echo=FALSE, message = FALSE, warning = FALSE, results = 'markdown', tidy=TRUE, fig.asp=0.618, out.width="70%", fig.align="center")
library(ggplot2)

library(hrbrthemes)


# For data manipulation
library(tidyverse)
library(magrittr)
library(ggplot2)
```

## 1. 

```{r, eval=TRUE, cache = FALSE, results = 'markdown'}
freeze_samples <- read_csv("/users/aperium/Dropbox/Projects/Chenopodium/Data/Freeze-Survival/freezesurvivaldata.csv") %>%
  #removing B12 because we don't have a 0 strat control
  filter(population != "B12") %>%
  mutate(color = case_when(
    morph == "LR" ~ "lr",
    morph == "DR" ~ "dr",
    morph == "BL" ~ "bl",
    TRUE ~ morph
  )) %>%
  # select(-morph, -X28) %>%
  dplyr::select(population, color, replicate, treatment, total_nofreeze, num_survived, total_afterfreeze) %>%
  mutate(population = as.factor(population), 
         color = as.factor(color), 
         replicate = as.factor(replicate)) %>%
  mutate(total_after_treatment = total_afterfreeze) %>%
  dplyr::select( -num_survived, -total_afterfreeze )

# get the no-freeze data from the same populations to serve as a control.
data <- read_csv("/Users/aperium/Dropbox/Projects/Chenopodium/Data/Stratification/raw_strat_germ_data.csv") %>% #added to address the off by one day problem
  filter(population %in% freeze_samples$population & treatment == 0 & days_of_incubation >= 0) %>%
  mutate( population = as.factor(population),
          color      = as.factor(color), 
          replicate = as.factor(replicate),
          germinated_this_day = ifelse(is.na(germinated_this_day),0,germinated_this_day),
          rotten = ifelse(is.na(rotten),0,rotten),
          malformed = ifelse(is.na(malformed),0,malformed),
          date       = as.Date(date, format = "%d-%b-%y")) %>%
  dplyr::select(-malformed, -rotten) %>%
  group_by(population, color, replicate, treatment) %>%
  summarise(total_nofreeze = sum(germinated_this_day)) %>%
  mutate(total_after_treatment = total_nofreeze)

# levels(data$population)
# levels(freeze_samples$population)

# names(freeze_samples)
# names(data)


combdata <- full_join(data, freeze_samples) %>%
  # dplyr::select( -total_nofreeze ) %>%
  ungroup() %>%
  mutate( color = if_else(color == "huauzontle", "nuttalliae", color)) %>%
  mutate( treatment = as.factor(treatment),
          color = as.factor(color),
          population = as.factor(population)) 

# THERE IS A MISSING ZEROS PROBLEM

# this will fill in all of the missing zeros.
variables <- names(combdata)
populations <- levels(combdata$population)
colors <- levels(combdata$color)
replicates <- levels(combdata$replicate)
treatments <- levels(combdata$treatment)
#
# for wild seed morphs
population_list <- c()
color_list <- c()
replicate_list <- c()
treatment_list <- c()
for(i in populations[1:6]) {
  for(j in colors[1:3]) {
    for(k in replicates[1]) {
      for(l in treatments) {
        population_list <- c(population_list,i)
        color_list <- c(color_list,j)
        replicate_list <- c(replicate_list,k)
        treatment_list <- c(treatment_list,l)
      }
    }
  }
}
blank_table <- tibble(
  population = population_list,
  color = color_list,
  replicate = replicate_list,
  treatment = treatment_list
)
#
# for nuttalliae
population_list <- c()
color_list <- c()
replicate_list <- c()
treatment_list <- c()
for(i in populations[7]) {
  for(j in colors[4]) {
    for(k in replicates) {
      for(l in treatments) {
        population_list <- c(population_list,i)
        color_list <- c(color_list,j)
        replicate_list <- c(replicate_list,k)
        treatment_list <- c(treatment_list,l)
      }
    }
  }
}
#
#put them together
blank_table %<>% full_join(
  tibble(
    population = population_list,
    color = color_list,
    replicate = replicate_list,
    treatment = treatment_list
  )
)
#
# and finally, join with existing data and
# add all those missing zeros
combdata %<>% full_join(blank_table) %>%
  mutate(total_after_treatment = dplyr::if_else(!is.na(total_after_treatment),total_after_treatment,as.integer(0),as.integer(0)),
         total_nofreeze = dplyr::if_else(!is.na(total_nofreeze),total_nofreeze,as.integer(0),as.integer(0))) 

# tweak some things
combdata %<>%
  mutate(population = as.factor(population),
         treatment = as.numeric(as.character(treatment))
         ) %>%
  mutate(
    proportional_after_treatment = total_after_treatment / 50,
    proportional_nofreeze = total_nofreeze / 50,
    treatment_in_days = treatment / 24) %>%
  mutate(color = factor(color, levels = unique(color[order(case_when(
    # this block re-orders the factors
    color == "nuttalliae" ~ 1,
    color == "lr"         ~ 2,
    color == "dr"         ~ 3,
    color == "bl"         ~ 4))]))) %>%
  mutate(population = as.factor(population),
         treatment = as.numeric(as.character(treatment))
         )

```

```{r}
fill_color <- c(nuttalliae = "goldenrod1",
                red = "firebrick1",
                black = "grey55",
                quinoa = "lemonchiffon",
                album = "grey33",
                macrocalycium = "firebrick")

fill_color2 <- c(nuttalliae = "#F3B35A", 
                red = "#540610", 
                black = "#4B4144", 
                quinoa = "#EBDE78", 
                album = "grey33",
                macrocalycium = "#492A26")

fill_color3 <- c(nuttalliae = rgb(colorRamp(c(fill_color[1], fill_color2[1]))(seq(0, 1, length = 3)), max = 255)[2], 
                red = rgb(colorRamp(c(fill_color[2], fill_color2[2]))(seq(0, 1, length = 5)), max = 255)[2], 
                black = rgb(colorRamp(c(fill_color[3], fill_color2[3]))(seq(0, 1, length = 3)), max = 255)[2], 
                quinoa = rgb(colorRamp(c(fill_color[4], fill_color2[4]))(seq(0, 1, length = 5)), max = 255)[4], 
                album = rgb(colorRamp(c(fill_color[5], fill_color2[5]))(seq(0, 1, length = 3)), max = 255)[2],
                macrocalycium = rgb(colorRamp(c(fill_color[6], fill_color2[6]))(seq(0, 1, length = 3)), max = 255)[2])

fill_color4 <- c(nuttalliae = rgb(colorRamp(c(fill_color3[1], "#FFFFFF"))(seq(0, 1, length = 3)), max = 255)[1], 
                red = rgb(colorRamp(c(fill_color3[2], "#FFFFFF"))(seq(0, 1, length = 3)), max = 255)[2], 
                black = rgb(colorRamp(c(fill_color3[3], "#FFFFFF"))(seq(0, 1, length = 3)), max = 255)[2], 
                quinoa = rgb(colorRamp(c(fill_color3[4], "#FFFFFF"))(seq(0, 1, length = 3)), max = 255)[2], 
                album = rgb(colorRamp(c(fill_color3[5], "#FFFFFF"))(seq(0, 1, length = 3)), max = 255)[2],
                macrocalycium = rgb(colorRamp(c(fill_color3[6], "#FFFFFF"))(seq(0, 1, length = 3)), max = 255)[2])

line_color <- c(nuttalliae = fill_color3[[1]], 
                red = fill_color3[[2]], 
                black = fill_color3[[3]], 
                quinoa = rgb(colorRamp(c(fill_color3[[4]], "#000000"))(seq(0, 1, length = 7)), max = 255)[2], 
                album = fill_color3[[5]],
                macrocalycium = fill_color3[[6]])

fill_colors <- c(lr = rgb(colorRamp(c(fill_color4[1], fill_color4[2]))(seq(0, 1, length = 5)), max = 255)[2],
                 dr = rgb(colorRamp(c(fill_color4[2], fill_color4[3]))(seq(0, 1, length = 3)), max = 255)[2],
                 bl = fill_color4[[3]],
                 nuttalliae = rgb(colorRamp(c(fill_color4[[1]], "#FFFF00"))(seq(0, 1, length = 5)), max = 255)[2])

line_colors <- c(lr = rgb(colorRamp(c(line_color[1], line_color[2]))(seq(0, 1, length = 5)), max = 255)[2],
                 dr = rgb(colorRamp(c(line_color[2], line_color[3]))(seq(0, 1, length = 3)), max = 255)[2],
                 bl = line_color[[3]],
                 nuttalliae = rgb(colorRamp(c(line_color[[1]], "#FFFF00"))(seq(0, 1, length = 5)), max = 255)[2])

theme_Maddison2018  <- function( ... ) {
  theme_minimal() +
  theme_ipsum_rc(grid = FALSE, base_size = 11.5 * 3/3, axis_title_size = 11.5 * 4/3, axis_title_face = "bold", axis_title_just = "mc") +
  theme(...)
}

theme_Maddison2018_legend <- function (...) {
  theme_Maddison2018(legend.text = element_text(size = 11.5 * 2/3, hjust=1, vjust=0.5), legend.title=element_text(face = "bold",size = 11.5 * 2.5/3), legend.key.height = unit(1.75, "char")) +
    theme(...)
}

ggα <- ggplot(data = combdata, aes(x = treatment, y = proportional_after_treatment, color = color, fill = color)) +
  # geom_boxplot() +
  geom_smooth(method = "lm", formula = y ~ x, size = 1/2, weight = 1) +
  geom_boxplot(data = combdata %>% filter(treatment==0), fill = NA, size = 1, width = 6) +
  geom_boxplot(data = combdata %>% filter(treatment==12), fill = NA, size = 1, width = 6) +
  geom_boxplot(data = combdata %>% filter(treatment==24), fill = NA, size = 1, width = 6) +
  geom_boxplot(data = combdata %>% filter(treatment==36), fill = NA, size = 1, width = 6) +
  scale_fill_manual(values = fill_colors) +
  scale_color_manual(values = line_colors) +
  # ylim(-0.5,NA) +
  scale_x_continuous(breaks = c(0,12,24,36), minor_breaks = c(12*0:36)) +
  xlab("imbibation period before freezing (hours)") + ylab("germination proportion") +
  theme_Maddison2018_legend()
#
width = 2750
height = width/1.61803399
# export PNG
png(file="/Users/aperium/Dropbox/Projects/Chenopodium/Drafts/Thesis/figures/freeze_alpha.png",w=width,h=height, res=300, units = "px")
grid::grid.newpage()
ggα
dev.off()

```

```{r stats}
lm(formula = proportional_after_treatment ~ color + treatment, data = combdata) %>% summary()

lm(formula = proportional_after_treatment ~ treatment, data = combdata %>% filter(color == "nuttalliae")) %>% summary()
lm(formula = proportional_after_treatment ~ treatment, data = combdata %>% filter(color == "lr")) %>% summary()
lm(formula = proportional_after_treatment ~ treatment, data = combdata %>% filter(color == "dr")) %>% summary()
lm(formula = proportional_after_treatment ~ treatment, data = combdata %>% filter(color == "bl")) %>% summary()

# aov(formula = proportional_after_treatment ~ color + treatment, data = combdata) %>% TukeyHSD("color")

# slope and intercept for the regression lines
reglinestats <- tibble(color = NA, intercept = NA, slope = NA, rsq = NA, adjrsq = NA)
for(i in unique(combdata$color)) {
  tmpmodel <- lm(proportional_after_treatment ~ treatment, data = filter(combdata, color == i))
  tmpsummary <- summary(tmpmodel)
  newtib <- tibble(color = i, 
         intercept = tmpmodel$coefficients[[1]],
         slope = tmpmodel$coefficients[[2]],
         rsq = tmpsummary$r.squared,
         adjrsq = tmpsummary$adj.r.squared)
  # print(newtib)
  ifelse(!is.na(reglinestats),
     reglinestats %<>% full_join(newtib),
     reglinestats <- newtib)
}
head(reglinestats)
```


```{r after_freeze_by_population, eval=FALSE, include=FALSE}
levels(combdata$population)


ggα_B3 <- combdata %>% filter(population == "B3") %>%
  ggplot(aes(x = treatment, y = proportional_after_treatment, color = color, fill = color)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x, size = 1/2, weight = 1) +
  scale_fill_manual(values = fill_colors) +
  scale_color_manual(values = line_colors) +
  scale_x_continuous(breaks = c(0,12,24,36), minor_breaks = c(12*0:36)) +
  xlab("incubation before freezing (hours)") + ylab("germination proportion") +
  theme_Maddison2018_legend()
#
ggα_B8 <- combdata %>% filter(population == "B8") %>%
  ggplot(aes(x = treatment, y = proportional_after_treatment, color = color, fill = color)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x, size = 1/2, weight = 1) +
  scale_fill_manual(values = fill_colors) +
  scale_color_manual(values = line_colors) +
  scale_x_continuous(breaks = c(0,12,24,36), minor_breaks = c(12*0:36)) +
  xlab("incubation before freezing (hours)") + ylab("germination proportion") +
  theme_Maddison2018_legend()
#
ggα_B14 <- combdata %>% filter(population == "B14") %>%
  ggplot(aes(x = treatment, y = proportional_after_treatment, color = color, fill = color)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x, size = 1/2, weight = 1) +
  scale_fill_manual(values = fill_colors) +
  scale_color_manual(values = line_colors) +
  scale_x_continuous(breaks = c(0,12,24,36), minor_breaks = c(12*0:36)) +
  xlab("incubation before freezing (hours)") + ylab("germination proportion") +
  theme_Maddison2018_legend()
#
ggα_B19 <- combdata %>% filter(population == "B19") %>%
  ggplot(aes(x = treatment, y = proportional_after_treatment, color = color, fill = color)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x, size = 1/2, weight = 1) +
  scale_fill_manual(values = fill_colors) +
  scale_color_manual(values = line_colors) +
  scale_x_continuous(breaks = c(0,12,24,36), minor_breaks = c(12*0:36)) +
  xlab("incubation before freezing (hours)") + ylab("germination proportion") +
  theme_Maddison2018_legend()
#
ggα_B33 <- combdata %>% filter(population == "B33") %>%
  ggplot(aes(x = treatment, y = proportional_after_treatment, color = color, fill = color)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x, size = 1/2, weight = 1) +
  scale_fill_manual(values = fill_colors) +
  scale_color_manual(values = line_colors) +
  scale_x_continuous(breaks = c(0,12,24,36), minor_breaks = c(12*0:36)) +
  xlab("incubation before freezing (hours)") + ylab("germination proportion") +
  theme_Maddison2018_legend()
#
ggα_B72 <- combdata %>% filter(population == "B72") %>%
  ggplot(aes(x = treatment, y = proportional_after_treatment, color = color, fill = color)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x, size = 1/2, weight = 1) +
  scale_fill_manual(values = fill_colors) +
  scale_color_manual(values = line_colors) +
  scale_x_continuous(breaks = c(0,12,24,36), minor_breaks = c(12*0:36)) +
  xlab("incubation before freezing (hours)") + ylab("germination proportion") +
  theme_Maddison2018_legend()
#
ggα_N3 <- combdata %>% filter(population == "N3") %>%
  ggplot(aes(x = treatment, y = proportional_after_treatment, color = color, fill = color)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x, size = 1/2, weight = 1) +
  scale_fill_manual(values = fill_colors) +
  scale_color_manual(values = line_colors) +
  scale_x_continuous(breaks = c(0,12,24,36), minor_breaks = c(12*0:36)) +
  xlab("incubation before freezing (hours)") + ylab("germination proportion") +
  theme_Maddison2018_legend()

ggα_B3
ggα_B8
ggα_B14
ggα_B19
ggα_B33
ggα_B72
ggα_N3
```

```{r before_vs_after, eval=FALSE, include=FALSE}
combdata_2 <- combdata %>%
  select(-proportional_nofreeze, -proportional_after_treatment) %>%
  filter(treatment > 0) %>%
  gather(key = "before_freeze", value = "germinations", total_nofreeze, total_after_treatment) %>%
  mutate(before_freeze = case_when(
           before_freeze == "total_after_treatment" ~ "after",
           before_freeze == "total_nofreeze" ~ "before")) %>%
  mutate(germination_proportion = germinations / 50,
         before_freeze = factor(before_freeze, levels = unique(before_freeze[order(case_when(
           # this block re-orders the factors
           before_freeze == "before" ~ 1,
           before_freeze == "after"         ~ 2))])))
    

ggβ1 <- combdata_2 %>%
  filter(color == "lr") %>%
  ggplot(aes(x = treatment, y = germination_proportion, color = color, fill = color, group = before_freeze)) +
    geom_boxplot(data = filter(combdata_2, color == "lr" & treatment == 12)) +
    geom_boxplot(data = filter(combdata_2, color == "lr" & treatment == 24)) +
    geom_boxplot(data = filter(combdata_2, color == "lr" & treatment == 36)) +
    scale_fill_manual(values = fill_colors) +
    scale_color_manual(values = line_colors) +
    scale_x_continuous(breaks = c(12,24,36), minor_breaks = c(12*1:3)) +
    xlab("incubation before freezing (hours)") + ylab("germination proportion") +
    theme_Maddison2018_legend()
#
ggβ2 <- combdata_2 %>%
  filter(color == "dr") %>%
  ggplot(aes(x = treatment, y = germination_proportion, color = color, fill = color, group = before_freeze)) +
    geom_boxplot(data = filter(combdata_2, color == "dr" & treatment == 12)) +
    geom_boxplot(data = filter(combdata_2, color == "dr" & treatment == 24)) +
    geom_boxplot(data = filter(combdata_2, color == "dr" & treatment == 36)) +
    scale_fill_manual(values = fill_colors) +
    scale_color_manual(values = line_colors) +
    scale_x_continuous(breaks = c(12,24,36), minor_breaks = c(12*1:3)) +
    xlab("incubation before freezing (hours)") + ylab("germination proportion") +
    theme_Maddison2018_legend()
#
ggβ3 <- combdata_2 %>%
  filter(color == "bl") %>%
  ggplot(aes(x = treatment, y = germination_proportion, color = color, fill = color, group = before_freeze)) +
    geom_boxplot(data = filter(combdata_2, color == "bl" & treatment == 12)) +
    geom_boxplot(data = filter(combdata_2, color == "bl" & treatment == 24)) +
    geom_boxplot(data = filter(combdata_2, color == "bl" & treatment == 36)) +
    scale_fill_manual(values = fill_colors) +
    scale_color_manual(values = line_colors) +
    scale_x_continuous(breaks = c(12,24,36), minor_breaks = c(12*1:3)) +
    xlab("incubation before freezing (hours)") + ylab("germination proportion") +
    theme_Maddison2018_legend()
#
ggβ4 <- combdata_2 %>%
  filter(color == "nuttalliae") %>%
  ggplot(aes(x = treatment, y = germination_proportion, color = color, fill = color, group = before_freeze)) +
    geom_boxplot(data = filter(combdata_2, color == "nuttalliae" & treatment == 12)) +
    geom_boxplot(data = filter(combdata_2, color == "nuttalliae" & treatment == 24)) +
    geom_boxplot(data = filter(combdata_2, color == "nuttalliae" & treatment == 36)) +
    scale_fill_manual(values = fill_colors) +
    scale_color_manual(values = line_colors) +
    scale_x_continuous(breaks = c(12,24,36), minor_breaks = c(12*1:3)) +
    xlab("incubation before freezing (hours)") + ylab("germination proportion") +
    theme_Maddison2018_legend()
#
ggβ1
ggβ2
ggβ3
ggβ4
```


